/**
 * Types for the drizzle-kit generated `migrations.js` bundle
 * (`driver: 'expo'` in drizzle.config.ts emits it next to this file).
 *
 * `migrations.js` is regenerated by `npx drizzle-kit generate`; this hand-written
 * declaration shadows it for TypeScript only. Its shape matches
 * node_modules/drizzle-orm/op-sqlite/migrator.d.ts.
 */
declare const bundle: {
  journal: {
    entries: {
      idx: number;
      when: number;
      tag: string;
      breakpoints: boolean;
    }[];
  };
  /** Keyed `m0000`, `m0001`, ... Values are the raw `.sql` file contents. */
  migrations: Record<string, string>;
};

export default bundle;
